<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223090407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE administrador (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ADMIN_EMAIL ON administrador (email)');
        $this->addSql('CREATE TABLE atributo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, producto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E6C7678A7645698E ON atributo (producto_id)');
        $this->addSql('CREATE TABLE atributo_valor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valor VARCHAR(100) NOT NULL, atributo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_767D2DFAA55FF1F3 ON atributo_valor (atributo_id)');
        $this->addSql('CREATE TABLE categoria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, fecha_nacimiento DATE NOT NULL, verificado_edad BOOLEAN NOT NULL, nif_cif VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CLIENTE_EMAIL ON cliente (email)');
        $this->addSql('CREATE TABLE combinacion_valor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notas TEXT DEFAULT NULL, combinacion_id INT NOT NULL, valor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_59C62A8DDFED3F8C ON combinacion_valor (combinacion_id)');
        $this->addSql('CREATE INDEX IDX_59C62A8D1EBE5BA7 ON combinacion_valor (valor_id)');
        $this->addSql('CREATE TABLE detalle_pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cantidad INT NOT NULL, precio_unitario NUMERIC(10, 2) NOT NULL, nombre_producto_hist VARCHAR(255) NOT NULL, pedido_id INT NOT NULL, combinacion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A834F5694854653A ON detalle_pedido (pedido_id)');
        $this->addSql('CREATE INDEX IDX_A834F569DFED3F8C ON detalle_pedido (combinacion_id)');
        $this->addSql('CREATE TABLE direccion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(50) NOT NULL, calle VARCHAR(255) NOT NULL, ciudad VARCHAR(255) NOT NULL, codiga_postal VARCHAR(20) NOT NULL, cliente_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F384BE95DE734E51 ON direccion (cliente_id)');
        $this->addSql('CREATE TABLE pago (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, monto NUMERIC(10, 2) NOT NULL, estado VARCHAR(50) NOT NULL, transaccion_id VARCHAR(255) DEFAULT NULL, pedido_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4DF5F3E4854653A ON pago (pedido_id)');
        $this->addSql('CREATE TABLE pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ffecha_pedido TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total NUMERIC(10, 2) NOT NULL, dir_envio_snapshot TEXT NOT NULL, dir_fact_snapshot TEXT NOT NULL, empaquetado_discreto BOOLEAN NOT NULL, cliente_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4EC16CEDE734E51 ON pedido (cliente_id)');
        $this->addSql('CREATE TABLE producto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion_general TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, categoria_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A7BB06153397707A ON producto (categoria_id)');
        $this->addSql('CREATE TABLE producto_combinacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sku VARCHAR(100) NOT NULL, precio NUMERIC(10, 2) NOT NULL, stock INT NOT NULL, producto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C7A708337645698E ON producto_combinacion (producto_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE atributo ADD CONSTRAINT FK_E6C7678A7645698E FOREIGN KEY (producto_id) REFERENCES producto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE atributo_valor ADD CONSTRAINT FK_767D2DFAA55FF1F3 FOREIGN KEY (atributo_id) REFERENCES atributo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE combinacion_valor ADD CONSTRAINT FK_59C62A8DDFED3F8C FOREIGN KEY (combinacion_id) REFERENCES producto_combinacion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE combinacion_valor ADD CONSTRAINT FK_59C62A8D1EBE5BA7 FOREIGN KEY (valor_id) REFERENCES atributo_valor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F5694854653A FOREIGN KEY (pedido_id) REFERENCES pedido (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F569DFED3F8C FOREIGN KEY (combinacion_id) REFERENCES producto_combinacion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE direccion ADD CONSTRAINT FK_F384BE95DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E4854653A FOREIGN KEY (pedido_id) REFERENCES pedido (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pedido ADD CONSTRAINT FK_C4EC16CEDE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE producto ADD CONSTRAINT FK_A7BB06153397707A FOREIGN KEY (categoria_id) REFERENCES categoria (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE producto_combinacion ADD CONSTRAINT FK_C7A708337645698E FOREIGN KEY (producto_id) REFERENCES producto (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE atributo DROP CONSTRAINT FK_E6C7678A7645698E');
        $this->addSql('ALTER TABLE atributo_valor DROP CONSTRAINT FK_767D2DFAA55FF1F3');
        $this->addSql('ALTER TABLE combinacion_valor DROP CONSTRAINT FK_59C62A8DDFED3F8C');
        $this->addSql('ALTER TABLE combinacion_valor DROP CONSTRAINT FK_59C62A8D1EBE5BA7');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F5694854653A');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F569DFED3F8C');
        $this->addSql('ALTER TABLE direccion DROP CONSTRAINT FK_F384BE95DE734E51');
        $this->addSql('ALTER TABLE pago DROP CONSTRAINT FK_F4DF5F3E4854653A');
        $this->addSql('ALTER TABLE pedido DROP CONSTRAINT FK_C4EC16CEDE734E51');
        $this->addSql('ALTER TABLE producto DROP CONSTRAINT FK_A7BB06153397707A');
        $this->addSql('ALTER TABLE producto_combinacion DROP CONSTRAINT FK_C7A708337645698E');
        $this->addSql('DROP TABLE administrador');
        $this->addSql('DROP TABLE atributo');
        $this->addSql('DROP TABLE atributo_valor');
        $this->addSql('DROP TABLE categoria');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE combinacion_valor');
        $this->addSql('DROP TABLE detalle_pedido');
        $this->addSql('DROP TABLE direccion');
        $this->addSql('DROP TABLE pago');
        $this->addSql('DROP TABLE pedido');
        $this->addSql('DROP TABLE producto');
        $this->addSql('DROP TABLE producto_combinacion');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
